
[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xffa198"
index = 17

[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x39c5cf"
green = "0x56d364"
magenta = "0xd2a8ff"
red = "0xffa198"
white = "0xb3b1ad"
yellow = "0xe3b341"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x3fb950"
magenta = "0xbc8cff"
red = "0xff7b72"
white = "0xb3b1ad"
yellow = "0xd29922"

[colors.primary]
background = "0x0d1117"
foreground = "0xb3b1ad"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "ComicShannsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Menlo"
style = "Bold Italic"

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
family = "ComicShannsMono Nerd Font"
style = "Regular"

[window]
blur = true 
decorations = "buttonless"
dynamic_padding = true
opacity = 0.75

[window.padding]
x = 30
y = 30
