# set Zsh as your default Tmux shell
set-option -g default-shell /bin/zsh

# UTF is great, let us use that

# Tmux should be pretty, we need 256 color for that
set -g default-terminal "screen-256color"

bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind | split-window -h
bind - split-window -v

bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
set -g mouse on

new-session


