#!/bin/bash

# Check if Homebrew is installed
if ! command -v brew &>/dev/null; then
    echo "Homebrew is not installed. Installing Homebrew..."
    
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
    if [[ $? -eq 0 ]]; then
        echo "Homebrew installed successfully."
        
        # Add Homebrew to PATH if necessary
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
    else
        echo "Failed to install Homebrew. Please check your internet connection and try again."
        exit 1
    fi
else
    echo "Homebrew is already installed. Skipping installation."
fi

# Verify installation
if command -v brew &>/dev/null; then
    echo "Homebrew is ready to use!"
else
    echo "Something went wrong. Homebrew is not working as expected."
    exit 1
fi

echo "Installing ghostty"
brew install --cask ghostty


echo "Installing aerospace..."
brew install --cask nikitabobko/tap/aerospace

echo "Installing Sketchybar"
brew tap FelixKratz/formulae
brew install sketchybar

#!/bin/bash

# Check if Homebrew is installed
if ! command -v brew &>/dev/null; then
    echo "Homebrew is not installed. Installing Homebrew..."
    
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
    if [[ $? -eq 0 ]]; then
        echo "Homebrew installed successfully."
        
        # Add Homebrew to PATH if necessary
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
    else
        echo "Failed to install Homebrew. Please check your internet connection and try again."
        exit 1
    fi
else
    echo "Homebrew is already installed. Skipping installation."
fi

# Verify installation
if command -v brew &>/dev/null; then
    echo "Homebrew is ready to use!"
else
    echo "Something went wrong. Homebrew is not working as expected."
    exit 1
fi

echo "Installing ghostty"
brew install --cask ghostty


echo "Installing aerospace..."
brew install --cask nikitabobko/tap/aerospace

echo "Installing Sketchybar"
brew tap FelixKratz/formulae
brew install sketchybar
brew install borders

brew install --cask font-hack-nerd-font
